<?php

namespace Database\Seeders;

use App\Models\RiskCell;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class RiskCellSeeder extends Seeder
{
    /**
     * Load the H3 grid generated by scripts/generate-cells.js (database/data/brunei-cells.json)
     * and upsert on h3_index so re-running this after regenerating the grid is idempotent.
     */
    public function run(): void
    {
        $path = database_path('data/brunei-cells.json');

        if (! file_exists($path)) {
            $this->command?->error("Grid file not found at {$path}. Run `node scripts/generate-cells.js` first.");

            return;
        }

        $cells = json_decode((string) file_get_contents($path), true);
        if (! is_array($cells) || $cells === []) {
            $this->command?->error("Grid file at {$path} is empty or invalid JSON.");

            return;
        }

        $now = Carbon::now();

        foreach (array_chunk($cells, 200) as $chunk) {
            $rows = array_map(static fn (array $cell): array => [
                'h3_index' => $cell['h3_index'],
                'lat' => $cell['lat'],
                'lng' => $cell['lng'],
                'district' => $cell['district'] ?? null,
                'elevation_m' => $cell['elevation_m'] ?? null,
                'drainage_capacity' => $cell['drainage_capacity'] ?? null,
                'historical_flood_events' => $cell['historical_flood_events'] ?? 0,
                'open_blockage_reports' => $cell['open_blockage_reports'] ?? 0,
                'current_score' => $cell['current_score'] ?? 0,
                'current_band' => $cell['current_band'] ?? 'low',
                'forecast_scores' => json_encode($cell['forecast_scores'] ?? []),
                'forecast_times' => json_encode($cell['forecast_times'] ?? []),
                'created_at' => $now,
                'updated_at' => $now,
            ], $chunk);

            // Only grid-shape/survey columns are updated on conflict — deliberately excludes
            // current_score/current_band/forecast_*/report counts, so re-running this seeder
            // (e.g. after regenerating the grid) never clobbers live risk:sync data.
            RiskCell::query()->upsert(
                $rows,
                ['h3_index'],
                ['lat', 'lng', 'district', 'elevation_m', 'drainage_capacity', 'updated_at']
            );
        }

        $this->command?->info(count($cells).' risk cells upserted from '.$path);
    }
}
