<?php

/**
 * Brunei drainage / sewer infrastructure risk zones for GIS maps and Ziqah AI context.
 *
 * risk_level: very_high | high | moderate | low
 * map_color:  red (very_high + high) | yellow (moderate) | green (low)
 */
return [

    'map_colors' => [
        'very_high' => ['fill' => '#dc2626', 'stroke' => '#991b1b', 'label' => 'Very high risk'],
        'high' => ['fill' => '#ef4444', 'stroke' => '#b91c1c', 'label' => 'High risk'],
        'moderate' => ['fill' => '#eab308', 'stroke' => '#a16207', 'label' => 'Moderate risk'],
        'low' => ['fill' => '#22c55e', 'stroke' => '#15803d', 'label' => 'Lower risk'],
    ],

    'weather' => [
        'default_lat' => 4.9031,
        'default_lng' => 114.9398,
        'location_name' => 'Bandar Seri Begawan, Brunei',
    ],

    'areas' => [
        [
            'id' => 'kedayan-d2',
            'name' => 'Kedayan (D2)',
            'risk_level' => 'very_high',
            'lat' => 4.8886,
            'lng' => 114.9412,
            'radius_km' => 1.8,
            'aliases' => ['kedayan', 'sungai kedayan', 'kampong sungai kedayan', 'd2', 'bandar riverbank'],
            'issues' => ['low elevation flooding', 'aging drainage', 'river contamination', 'overloaded sewer', 'clogged monsoon drains', 'odor near waterways'],
            'notes' => 'One of the highest leak-risk zones in Brunei-Muara studies; near Sungai Kedayan.',
        ],
        [
            'id' => 'damuan-d6',
            'name' => 'Damuan (D6)',
            'risk_level' => 'very_high',
            'lat' => 4.9280,
            'lng' => 114.9180,
            'radius_km' => 1.6,
            'aliases' => ['damuan', 'd6'],
            'issues' => ['pipeline leaks', 'drainage overflow', 'flash flooding', 'sewage backflow', 'river pollution'],
            'notes' => 'Repeatedly flagged as failure-prone water infrastructure in Brunei-Muara studies.',
        ],
        [
            'id' => 'sungai-brunei-kampong-ayer',
            'name' => 'Sungai Brunei / Kampong Ayer',
            'risk_level' => 'very_high',
            'lat' => 4.8840,
            'lng' => 114.9440,
            'radius_km' => 2.0,
            'aliases' => ['kampong ayer', 'kampung ayer', 'sungai brunei', 'water village', 'bandar waterfront'],
            'issues' => ['tidal influence', 'sediment buildup', 'wastewater discharge', 'drain blockage', 'odor accumulation'],
            'notes' => 'Clogged monsoon drains and septic overflow during storms are common concerns.',
        ],
        [
            'id' => 'subok-belimbing-berakas',
            'name' => 'Subok / Belimbing Berakas',
            'risk_level' => 'high',
            'lat' => 4.9620,
            'lng' => 114.9680,
            'radius_km' => 2.2,
            'aliases' => ['subok', 'belimbing', 'belimbing berakas', 'kampong subok'],
            'issues' => ['pipe leaks', 'drainage overload', 'flooding', 'sewer pressure issues'],
            'notes' => 'Often listed in water disruption and low-pressure notices.',
        ],
        [
            'id' => 'kota-batu-kianggeh',
            'name' => 'Kota Batu / Kianggeh',
            'risk_level' => 'high',
            'lat' => 4.8780,
            'lng' => 114.9520,
            'radius_km' => 2.0,
            'aliases' => ['kota batu', 'kianggeh'],
            'issues' => ['clogged drains', 'localized flooding', 'sewer overflow after storms'],
            'notes' => 'Waterway proximity and older urban drainage increase vulnerability.',
        ],
        [
            'id' => 'gadong-menglait-batu-bersurat',
            'name' => 'Gadong / Menglait / Batu Bersurat',
            'risk_level' => 'high',
            'lat' => 4.9120,
            'lng' => 114.9050,
            'radius_km' => 2.5,
            'aliases' => ['gadong', 'menglait', 'batu bersurat', 'pengkalan gadong'],
            'issues' => ['underground pipe failures', 'water line leaks', 'drainage overload', 'commercial sewage stress'],
            'notes' => 'Heavily urbanized; JKR emergency repairs recur in commercial strips.',
        ],
        [
            'id' => 'bunut-jalan-haji-halus',
            'name' => 'Bunut / Jalan Haji Halus',
            'risk_level' => 'high',
            'lat' => 4.9310,
            'lng' => 114.9280,
            'radius_km' => 1.5,
            'aliases' => ['bunut', 'jalan haji halus', 'tanjung bunut'],
            'issues' => ['aging underground pipes', 'sewer collapse risk', 'backflow during rain'],
            'notes' => 'JKR has repaired deep underground sewer pipes here with road closures.',
        ],
        [
            'id' => 'panaga-belait',
            'name' => 'Panaga Housing Scheme (Belait)',
            'risk_level' => 'high',
            'lat' => 4.6040,
            'lng' => 114.2290,
            'radius_km' => 1.8,
            'aliases' => ['panaga', 'panaga housing'],
            'issues' => ['clogged sewers', 'vacuum sewer problems', 'maintenance backlog'],
            'notes' => 'Government statements have acknowledged recurring sewer maintenance issues.',
        ],
        [
            'id' => 'bukit-bilid-paya-namurai',
            'name' => 'Jalan Bukit Bilid / Jalan Paya Namurai',
            'risk_level' => 'high',
            'lat' => 4.9460,
            'lng' => 114.9380,
            'radius_km' => 1.4,
            'aliases' => ['bukit bilid', 'paya namurai', 'jalan bukit bilid', 'jalan paya namurai'],
            'issues' => ['drainage unable to handle heavy rain', 'storm overflow', 'redesign needed'],
            'notes' => 'Investigations found drainage capacity limits during heavy rainfall.',
        ],
        [
            'id' => 'lambak-kanan',
            'name' => 'Lambak Kanan',
            'risk_level' => 'moderate',
            'lat' => 4.9510,
            'lng' => 114.9450,
            'radius_km' => 1.5,
            'aliases' => ['lambak kanan', 'lambak'],
            'issues' => ['low pressure events', 'pipe leaks', 'drainage maintenance'],
            'notes' => 'Moderate recurring infrastructure notices.',
        ],
        [
            'id' => 'sungai-akar',
            'name' => 'Sungai Akar',
            'risk_level' => 'moderate',
            'lat' => 4.9380,
            'lng' => 114.9580,
            'radius_km' => 1.4,
            'aliases' => ['sungai akar'],
            'issues' => ['pipe leaks', 'localized flooding'],
            'notes' => null,
        ],
        [
            'id' => 'anggerek-desa',
            'name' => 'Anggerek Desa',
            'risk_level' => 'moderate',
            'lat' => 4.9080,
            'lng' => 114.9280,
            'radius_km' => 1.3,
            'aliases' => ['anggerek desa', 'anggerek'],
            'issues' => ['drainage maintenance', 'low pressure'],
            'notes' => null,
        ],
        [
            'id' => 'mata-mata',
            'name' => 'Mata-Mata',
            'risk_level' => 'moderate',
            'lat' => 4.9180,
            'lng' => 114.9220,
            'radius_km' => 1.3,
            'aliases' => ['mata-mata', 'mata mata'],
            'issues' => ['drainage alerts', 'pipe incidents'],
            'notes' => null,
        ],
        [
            'id' => 'salambigar',
            'name' => 'Salambigar',
            'risk_level' => 'moderate',
            'lat' => 4.9420,
            'lng' => 114.9720,
            'radius_km' => 1.5,
            'aliases' => ['salambigar'],
            'issues' => ['flooding complaints', 'infrastructure stress'],
            'notes' => null,
        ],
        [
            'id' => 'sungai-tilong',
            'name' => 'Sungai Tilong',
            'risk_level' => 'moderate',
            'lat' => 4.8720,
            'lng' => 114.9180,
            'radius_km' => 1.4,
            'aliases' => ['sungai tilong'],
            'issues' => ['drainage maintenance'],
            'notes' => null,
        ],
        [
            'id' => 'serusop',
            'name' => 'Serusop',
            'risk_level' => 'moderate',
            'lat' => 4.9480,
            'lng' => 114.9280,
            'radius_km' => 1.4,
            'aliases' => ['serusop'],
            'issues' => ['low pressure', 'pipe leaks'],
            'notes' => null,
        ],
        [
            'id' => 'kiarong',
            'name' => 'Kiarong',
            'risk_level' => 'moderate',
            'lat' => 4.9020,
            'lng' => 114.9180,
            'radius_km' => 1.3,
            'aliases' => ['kiarong'],
            'issues' => ['drainage maintenance'],
            'notes' => null,
        ],
        [
            'id' => 'lumapas',
            'name' => 'Lumapas',
            'risk_level' => 'moderate',
            'lat' => 4.8580,
            'lng' => 114.9020,
            'radius_km' => 1.8,
            'aliases' => ['lumapas'],
            'issues' => ['flooding-related complaints'],
            'notes' => null,
        ],
        [
            'id' => 'tanah-jambu',
            'name' => 'Tanah Jambu',
            'risk_level' => 'moderate',
            'lat' => 4.9720,
            'lng' => 114.9580,
            'radius_km' => 1.6,
            'aliases' => ['tanah jambu'],
            'issues' => ['infrastructure stress'],
            'notes' => null,
        ],
        [
            'id' => 'berakas-ab',
            'name' => "Berakas 'A' / 'B'",
            'risk_level' => 'moderate',
            'lat' => 4.9450,
            'lng' => 114.9850,
            'radius_km' => 2.0,
            'aliases' => ['berakas', "berakas a", "berakas b", 'berakas a/b'],
            'issues' => ['water disruption notices', 'drainage maintenance'],
            'notes' => null,
        ],
    ],

];
